services:
  - type: web
    name: fullstack-backend
    env: node
    plan: free
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGO_URI
        value: mongodb+srv://mohit_yadav:Captain1%40@cluster0.elsqwgt.mongodb.net/Cluster0?retryWrites=true&w=majority&appName=Cluster0
      - key: JWT_SECRET
        value: your_jwt_secret_key
      - key: PORT
        value: 5000

  - type: static
    name: fullstack-frontend
    rootDir: frontend
    buildCommand: cd vite-project && npm run build
    staticPublishPath: vite-project/dist
    autoDeploy: true
